# Site settings
lang: en
title: Roffild’s Library for MQL5 (MetaTrader) with Java, Apache Spark, AWS
name: Roffild’s Library
url: https://roffild.com
google: UA-121315607-1

include:
  - _*.*

exclude:
  - _config.yml
  - CNAME
  - create_site.py

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "*_ru.*"
    values:
      lang: ru
