# Site settings
title: Roffild’s Library
name: Roffild’s Library
url: https://roffild.com

include:
  - _*.*

exclude:
  - _config.yml
  - CNAME
  - create_site.py

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      description: An attempt to implement the features on MQL5, which have long become the standard for popular programming languages.
  -
    scope:
      path: "/ru/*"
    values:
      lang: ru
      description: Попытка реализовать возможности на MQL5, которые уже давно стали стандартом для популярных языков программирования.
