# Site settings
title: "Roffild’s Library"
name: "Roffild’s Library"
url: "https://roffild.com"

include:
  - _*.*

exclude:
  - _config.yml
  - CNAME
  - create_site.py

# Build settings
markdown: kramdown
