# Site settings
title: Roffild’s Library for MQL5 (MetaTrader) with Java, Apache Spark, AWS
name: Roffild’s Library
url: https://roffild.com

include:
  - _*.*

exclude:
  - _config.yml
  - CNAME
  - create_site.py

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      description: Transform your plain text into static websites and blogs
  -
    scope:
      path: "*_ru.*"
    values:
      lang: ru
      description: русский текст
