var annotated_dup =
[
    [ "CArrayList", "class_c_array_list.html", "class_c_array_list" ],
    [ "CArrayListClass", "class_c_array_list_class.html", "class_c_array_list_class" ],
    [ "CCsvFile", "class_c_csv_file.html", "class_c_csv_file" ],
    [ "CForestSerializer", "class_c_forest_serializer.html", null ],
    [ "CLog4Mql", "class_c_log4_mql.html", "class_c_log4_mql" ],
    [ "CLog4MqlFile", "class_c_log4_mql_file.html", "class_c_log4_mql_file" ],
    [ "CMLPDataFile", "class_c_m_l_p_data_file.html", "class_c_m_l_p_data_file" ],
    [ "COrderData", "class_c_order_data.html", "class_c_order_data" ],
    [ "COrderDataObject", "class_c_order_data_object.html", "class_c_order_data_object" ],
    [ "COrderSql", "class_c_order_sql.html", "class_c_order_sql" ],
    [ "COrderSqlObject", "class_c_order_sql_object.html", "class_c_order_sql_object" ],
    [ "COrderSqlObjectCast", "class_c_order_sql_object_cast.html", "class_c_order_sql_object_cast" ],
    [ "CSerialization", "class_c_serialization.html", "class_c_serialization" ],
    [ "CSerializationRead", "class_c_serialization_read.html", "class_c_serialization_read" ],
    [ "CSqlFile", "class_c_sql_file.html", "class_c_sql_file" ],
    [ "CSqlObject", "class_c_sql_object.html", "class_c_sql_object" ],
    [ "CSqlObjectSnapShot", "class_c_sql_object_snap_shot.html", "class_c_sql_object_snap_shot" ],
    [ "CStatistic", "class_c_statistic.html", "class_c_statistic" ],
    [ "CStatisticObject", "class_c_statistic_object.html", "class_c_statistic_object" ],
    [ "CTesterSql", "class_c_tester_sql.html", "class_c_tester_sql" ],
    [ "CToIndicator", "class_c_to_indicator.html", "class_c_to_indicator" ],
    [ "CUnitTest", "class_c_unit_test.html", "class_c_unit_test" ],
    [ "SToIndicator_Data", "struct_s_to_indicator___data.html", "struct_s_to_indicator___data" ],
    [ "SToIndicator_Parameter", "struct_s_to_indicator___parameter.html", "struct_s_to_indicator___parameter" ]
];